### ISSUE TITLE
algorithm breaks for the following string `arg`

### ISSUE THREAD

**Issue by jevzee** [jevzee/periodify#1]
ERROR LOG:
```
TypeError: Cannot read property 'symbol' of undefined
    at periodify (/Users/jevzee/workspace/test/node_modules/periodify/lib/periodify.js:48:40)
    at main (/Users/jevzee/workspace/test/node_modules/periodify/lib/periodify.js:4:13)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:392:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)

```

**Comment by jevzee** [comment]
fixed in 84fea5b
